repos:
-   repo: https://github.com/pycqa/flake8
    rev: '6.0.0'
    hooks:
    -   id: flake8
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v2.0.1
    hooks:
    -   id: autopep8
-   repo: local
    hooks:
    -   id: pytest
        name: pytest
        entry: python api/hooks/pytest.py
        language: python
        types: [python]
-   repo: local
    hooks:
    -   id: typos
        name: typos
        entry: python api/hooks/typos.py
        language: python
        types: [python]
