version: '3'
services:
  gkfeed:
    build:
      context: .
    volumes:
      - gkfeed_data:/data
    env_file:
      - .env
    ports:
      - "8000:8000"
    container_name: gkfeed
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    container_name: gkfeed-redis
volumes:
  gkfeed_data:
