name: Deploy-Api

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: test
        uses: fifsky/ssh-action@master
        with:
          command: |
            kill -9 $(pgrep -f feed) || echo "Feed isn't running"
            cd github/gakawarstone/feed/api
            ls
            git fetch && git pull
            pipenv install
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USER_NAME }}
          key: ${{ secrets.PRIVATE_KEY}}
