name: Deploy-Api
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy with SSH
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd github/gakawarstone/feed/api
            pipenv run gitup
            pipenv run drestart
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USER_NAME }}
          key: ${{ secrets.PRIVATE_KEY}}
