name: Deploy-Api

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Set up SSH
      run: |
        echo "${{ secrets.PRIVATE_KEY }}" | tr -d '\r' > ssh.pem
        chmod 600 ssh.pem
        ssh-keyscan ${{ secrets.HOST }} >> ~/.ssh/known_hosts

    - name: Deploy
      run: |
        ssh -i ssh.pem ${{ secrets.USERNAME }}@${{ secrets.HOST }}
        cd {{ secrets.PTOJECT_PATH }}/api
